name: Offices API Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Restore and Build
        run: |
          dotnet restore InnoClinic.OfficesAPI/InnoClinic.OfficesAPI.sln -p:Configuration=Release
          dotnet build InnoClinic.OfficesAPI/InnoClinic.OfficesAPI.sln --configuration Release --no-restore